import { NextResponse } from 'next/server';

export async function GET() {
  const mockPreview = {
    columns: [
      'Artist',
      'Release Title',
      'Song Title',
      'ISRC',
      'UPC',
      'Country of Sale',
      'Sales Type',
      'Units Sold',
      'Total Earned',
      'Currency',
      'Sales Period',
      'Store Name',
    ],
    rows: [
      {
        Artist: 'John Doe',
        'Release Title': 'My First Album',
        'Song Title': 'Summer Vibes',
        ISRC: 'USRC12345678',
        UPC: '0123456789012',
        'Country of Sale': 'FR',
        'Sales Type': 'Stream',
        'Units Sold': '1523',
        'Total Earned': '5.23',
        Currency: 'EUR',
        'Sales Period': '2024-01',
        'Store Name': 'Spotify',
      },
      {
        Artist: 'John Doe',
        'Release Title': 'My First Album',
        'Song Title': 'Winter Dreams',
        ISRC: 'USRC12345679',
        UPC: '0123456789012',
        'Country of Sale': 'US',
        'Sales Type': 'Download',
        'Units Sold': '42',
        'Total Earned': '29.40',
        Currency: 'USD',
        'Sales Period': '2024-01',
        'Store Name': 'iTunes',
      },
      {
        Artist: 'Jane Smith',
        'Release Title': 'Electric Nights',
        'Song Title': 'Neon Lights',
        ISRC: 'USRC98765432',
        UPC: '0987654321098',
        'Country of Sale': 'DE',
        'Sales Type': 'Stream',
        'Units Sold': '8921',
        'Total Earned': '31.22',
        Currency: 'EUR',
        'Sales Period': '2024-01',
        'Store Name': 'Deezer',
      },
      {
        Artist: 'Jane Smith',
        'Release Title': 'Electric Nights',
        'Song Title': 'City Pulse',
        ISRC: 'USRC98765433',
        UPC: '0987654321098',
        'Country of Sale': 'GB',
        'Sales Type': 'Stream',
        'Units Sold': '4532',
        'Total Earned': '15.87',
        Currency: 'GBP',
        'Sales Period': '2024-01',
        'Store Name': 'Apple Music',
      },
      {
        Artist: 'The Collective',
        'Release Title': 'Underground Sessions',
        'Song Title': 'Basement Beat',
        ISRC: 'USRC55555555',
        UPC: '5555555555555',
        'Country of Sale': 'JP',
        'Sales Type': 'Stream',
        'Units Sold': '12453',
        'Total Earned': '4980.00',
        Currency: 'JPY',
        'Sales Period': '2024-01',
        'Store Name': 'Spotify',
      },
    ],
    total_rows: 15234,
  };

  return NextResponse.json(mockPreview);
}
